### ISSUE TITLE
StyleCop should not be part of the nuget package

### ISSUE THREAD

**Issue by Frosco** [aljazsim/defensive-programming-framework-for-net#2]
Hi!

This repo and the corresponding NuGet package use StyleCop. This will activate the warnings even for the project which references the defensive programming framework. In general it should be up to the developers which style they want to use and how they want to enforce it.

**Comment by aljazsim** [comment]
I was not aware that was happening, since I use StyleCop on all my projects. And yes, you are right, the developers should have the option to use it or not. I will update the packaging process to remove the StyleCop reference. Thanks for letting me know!

**Comment by aljazsim** [comment]
I have updated the nuget package publishing script to remove StyleCop and FxCop dependencies prior to publishing.
